# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Abel Nieva
subtitle: Front End Software Developer
email: abel@abelnieva.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador de software enfocado en JavaScript y Angular, apasionado del código limpio y la usabilidad. Escribo
  sobre quién soy, qué pienso y las lecturas que hago.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abelnieva.com" # the base hostname & protocol for your site
enforce_ssl: abelnieva.com
twitter_username: abelnieva

# Build settings
markdown: kramdown
theme: alna-jekyll-theme
gems:
  - jekyll-feed
exclude: [Gemfile, Gemfile.lock, vendor, LICENSE.txt, README.md]
excerpt_separator: <!--more-->
collections:
  books:
    output: true

# Site content
about: >
  Este sitio web es propulsado por <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> y alojado en
  <a href="https://github.com/" target="_blank">GitHub</a>. <a href="/feed.xml">Suscríbete al feed RSS de
  artículos</a>.
copyright: Copyright © <span itemprop="copyrightYear">2016-2017</span> Abel Nieva. Todos los derechos reservados.
author:
  name: Abel Nieva
  avatar: /assets/img/abelnieva.avatar.jpg
  avatar2x: /assets/img/abelnieva.avatar@2x.jpg
  avatar_alt: Abel Nieva foto de perfil
  bio: >
    ¡Hola! Soy Abel Nieva, un desarrollador de software enfocado en JavaScript y Angular, apasionado del código limpio y
    la usabilidad. Escribo sobre quién soy, qué pienso y las lecturas que hago.
social_media:
  - name: Twitter
    link: https://twitter.com/abelnieva
  - name: GitHub
    link: https://github.com/abel-nieva
  - name: LinkedIn
    link: https://www.linkedin.com/in/abel-nieva
